# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

def shared_pods
  # Dependency injection framework for Swift with iOS/macOS/Linux
  pod 'Swinject'
  
  # A clean and lightweight progress HUD for your iOS and tvOS app.
  pod 'SVProgressHUD'
  
  # Convenient logging during development & release in Swift 3, 4 & 5
  pod 'SwiftyBeaver'
  
  # A Swift Autolayout DSL for iOS & OS X
  pod 'SnapKit'
  
  # A beautiful and flexible text field control implementation of "Float Label Pattern". Written in Swift.
  pod 'SkyFloatingLabelTextField'
  
  # Codeless drop-in universal library allows to prevent issues of keyboard sliding up and cover UITextField/UITextView. Neither need to write any code nor any setup required and much more.
  pod 'IQKeyboardManagerSwift'
  
  # Promises for Swift & ObjC.
  pod 'PromiseKit'
  
  # Unidirectional Data Flow in Swift - Inspired by Redux
  pod 'ReSwift'
  
  # Reactive Programming in Swift
  pod 'RxCocoa'
  pod 'RxSwift'
  
  # Elegant HTTP Networking in Swift
  pod 'Alamofire'
  
  pod 'TSwiftHelper'
end

target 'weather_forecast_dev' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  shared_pods
  
  # Pods for weather_forecast
  target 'weather_forecastTests' do
    inherit! :search_paths
    # Pods for testing
    shared_pods
  end

  target 'weather_forecastUITests' do
    # Pods for testing
    shared_pods
  end

end

target 'weather_forecast_pro' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  shared_pods
  
  # Pods for weather_forecast
  target 'weather_forecastTests' do
    inherit! :search_paths
    # Pods for testing
    shared_pods
  end

  target 'weather_forecastUITests' do
    # Pods for testing
    shared_pods
  end

end
